"""
Tests for scobelix.solgen - the opcode/AST -> Solidity generator.

Two levels of coverage:
  - structural checks on the generated text (state vars, function shape,
    confidence/warnings reporting) that don't need any external tool;
  - an end-to-end check that the generated Solidity actually compiles with
    solc, skipped automatically if solc isn't installed (it's the strongest
    signal this module can produce - solgen's whole point is to hand
    downstream tools something they can compile).
"""

import os
import shutil
import subprocess
from pathlib import Path

import pytest

from scobelix.decompiler import decompile_bytecode
from scobelix.solgen import generate_solidity

FIXTURES_DIR = Path(__file__).parent / "fixtures" / "bytecode"

SOLC = shutil.which("solc")


def _load(name: str) -> str:
    return (FIXTURES_DIR / f"{name}.hex").read_text().strip()


def _generate(name: str):
    d = decompile_bytecode(_load(name))
    return generate_solidity(d)


def test_simple_token_state_vars_and_fallback_shape():
    r = _generate("SimpleToken")

    assert "// GENERATED BY SCOBELIX SOLGEN" in r.solidity
    assert "pragma solidity" in r.solidity
    assert "mapping(uint256 => uint256) internal stor0;" in r.solidity
    assert "uint256 internal stor1;" in r.solidity
    assert "fallback(bytes calldata) external payable returns (bytes memory)" in r.solidity
    assert r.confidence["_fallback"] == "high"


def test_eip1967_proxy_delegatecall_translated():
    r = _generate("Eip1967Proxy")

    assert ".delegatecall(msg.data)" in r.solidity
    assert "approximation" in r.solidity  # never hides that this is a guess


def test_sumloop_loopvar_declared_once_and_reused():
    r = _generate("SumLoop")

    # declared exactly once, at function scope - not re-declared inside the
    # while body or redeclared by the continue-branch setvar
    assert r.solidity.count("uint256 loopvar_0;") == 1
    assert "while (" in r.solidity
    assert "loopvar_0 = " in r.solidity


def test_nested_mapping_gets_correct_depth_and_no_crash():
    # regression: a single loc used as both allowances[a] (depth 1) and
    # allowances[a][b] (depth 2) used to crash _resolve_storage
    # (TypeError: unhashable type: 'list', the inner ("map", ...) node used
    # as a dict key) and, once that was fixed, declared the slot as a
    # single-level mapping(uint256=>uint256) - a second index into that is a
    # solc type error, not just an approximation.
    r = _generate("NestedStructMapping")

    assert "mapping(uint256 => mapping(uint256 => uint256))" in r.solidity


def test_yul_heavy_shift_and_mask_reconstructed():
    r = _generate("YulHeavy")

    # shl(4, and(a, 0xff)) - offset==0 with a non-zero shl, the case that
    # used to fall through to an unresolved-opcode placeholder.
    assert "(_param1 & 255) << 4" in r.solidity


def test_vault_bool_param_coerced_not_left_as_bool_literal():
    r = _generate("Vault")

    # setPaused(bool) stores the calldata-decoded bool into a uint256 slot;
    # emitting the raw Solidity `true`/`false` literal there used to produce
    # `stor2 = (true & 255);` - a bool/int type error.
    assert "true & 255" not in r.solidity
    assert "= (true & 255)" not in r.solidity


def test_known_event_resolved_with_real_name_and_args():
    r = _generate("EventsEmitter")

    assert "event Transfer(address indexed from, address indexed to, uint256 value);" in r.solidity
    assert "emit Transfer(" in r.solidity
    # args must land back in declaration order: from, to, value
    assert "emit Transfer(address(uint160" in r.solidity


def test_unknown_event_falls_back_to_generic_placeholder():
    r = _generate("EventsEmitter")

    # Ping(uint256) isn't in the well-known table - must not be silently
    # invented as a fake Ping(...) event with guessed types.
    assert "event Ping" not in r.solidity
    assert "ScobelixUnresolvedEvent" in r.solidity


def test_diamond_style_dispatch_two_calls_each_check_their_own_result():
    # regression: vm.py's call-id counter (e.g. "delegatecall_10") is shared
    # with unrelated operations (mload-introduced temporaries included), so
    # a naive per-function "1st call = _1, 2nd call = _2" renumbering in
    # solgen never matches it - the second call's success check used to
    # resolve to an unrelated, always-zero placeholder, making it look like
    # every call after the first had failed (an always-taken revert, not
    # just an approximation).
    r = _generate("MiniDiamond")

    assert r.solidity.count(".delegatecall(msg.data)") == 2
    assert "if ((!delegatecall_ok_1))" in r.solidity
    assert "if ((!delegatecall_ok_2))" in r.solidity
    # the old bug fell back to an unrelated, always-zero placeholder
    # ("stor_extra_N") for the second call's success check instead of its
    # own result variable.
    assert "stor_extra" not in r.solidity


def test_diamond_selector_mask_reconstructed_not_approximated():
    r = _generate("MiniDiamond")
    assert "not exactly reconstructed" not in r.solidity
    assert not r.warnings


def test_unresolvable_function_gets_explicit_stub_not_silently_dropped():
    fake_json = {
        "stor_defs": [],
        "functions": [],
        "problems": {"0xdeadbeef": "someFunction(uint256)"},
    }

    class FakeDecompilation:
        json = fake_json

    r = generate_solidity(FakeDecompilation())

    assert "0xdeadbeef" in r.solidity
    assert "someFunction(uint256)" in r.solidity
    assert "decompilation failed" in r.solidity


@pytest.mark.skipif(SOLC is None, reason="solc not installed")
@pytest.mark.parametrize(
    "name",
    [
        "SimpleToken",
        "Eip1967Proxy",
        "SumLoop",
        "NestedStructMapping",
        "YulHeavy",
        "Vault",
        "EventsEmitter",
        "MiniDiamond",
    ],
)
def test_generated_solidity_actually_compiles(name, tmp_path):
    r = _generate(name)
    sol_path = tmp_path / f"{name}.sol"
    sol_path.write_text(r.solidity)

    # SOLC_VERSION pins solc-select installs regardless of what global
    # version is (or isn't) configured in the current shell/environment - a
    # plain, non-solc-select `solc` binary just ignores the extra env var.
    env = dict(os.environ, SOLC_VERSION="0.8.19")
    result = subprocess.run(
        [SOLC, "--bin", str(sol_path)],
        capture_output=True,
        text=True,
        timeout=60,
        env=env,
    )

    assert result.returncode == 0, (
        f"generated Solidity for {name} failed to compile:\n"
        f"{result.stderr}\n\n--- generated source ---\n{r.solidity}"
    )
    assert "Binary:" in result.stdout
