"""
Tests for panoramix.solgen - the opcode/AST -> Solidity generator.

Two levels of coverage:
  - structural checks on the generated text (state vars, function shape,
    confidence/warnings reporting) that don't need any external tool;
  - an end-to-end check that the generated Solidity actually compiles with
    solc, skipped automatically if solc isn't installed (it's the strongest
    signal this module can produce - solgen's whole point is to hand
    downstream tools something they can compile).
"""

import os
import shutil
import subprocess
from pathlib import Path

import pytest

from panoramix.decompiler import decompile_bytecode
from panoramix.solgen import generate_solidity

FIXTURES_DIR = Path(__file__).parent / "fixtures" / "bytecode"

SOLC = shutil.which("solc")


def _load(name: str) -> str:
    return (FIXTURES_DIR / f"{name}.hex").read_text().strip()


def _generate(name: str):
    d = decompile_bytecode(_load(name))
    return generate_solidity(d)


def test_simple_token_state_vars_and_fallback_shape():
    r = _generate("SimpleToken")

    assert "// GENERATED BY SCOBELIX SOLGEN" in r.solidity
    assert "pragma solidity" in r.solidity
    assert "mapping(uint256 => uint256) internal stor0;" in r.solidity
    assert "uint256 internal stor1;" in r.solidity
    assert "fallback(bytes calldata) external payable returns (bytes memory)" in r.solidity
    assert r.confidence["_fallback"] == "high"


def test_eip1967_proxy_delegatecall_translated():
    r = _generate("Eip1967Proxy")

    assert ".delegatecall(msg.data)" in r.solidity
    assert "approximation" in r.solidity  # never hides that this is a guess


def test_sumloop_loopvar_declared_once_and_reused():
    r = _generate("SumLoop")

    # declared exactly once, at function scope - not re-declared inside the
    # while body or redeclared by the continue-branch setvar
    assert r.solidity.count("uint256 loopvar_0;") == 1
    assert "while (" in r.solidity
    assert "loopvar_0 = " in r.solidity


def test_unresolvable_function_gets_explicit_stub_not_silently_dropped():
    fake_json = {
        "stor_defs": [],
        "functions": [],
        "problems": {"0xdeadbeef": "someFunction(uint256)"},
    }

    class FakeDecompilation:
        json = fake_json

    r = generate_solidity(FakeDecompilation())

    assert "0xdeadbeef" in r.solidity
    assert "someFunction(uint256)" in r.solidity
    assert "decompilation failed" in r.solidity


@pytest.mark.skipif(SOLC is None, reason="solc not installed")
@pytest.mark.parametrize("name", ["SimpleToken", "Eip1967Proxy", "SumLoop"])
def test_generated_solidity_actually_compiles(name, tmp_path):
    r = _generate(name)
    sol_path = tmp_path / f"{name}.sol"
    sol_path.write_text(r.solidity)

    # SOLC_VERSION pins solc-select installs regardless of what global
    # version is (or isn't) configured in the current shell/environment - a
    # plain, non-solc-select `solc` binary just ignores the extra env var.
    env = dict(os.environ, SOLC_VERSION="0.8.19")
    result = subprocess.run(
        [SOLC, "--bin", str(sol_path)],
        capture_output=True,
        text=True,
        timeout=60,
        env=env,
    )

    assert result.returncode == 0, (
        f"generated Solidity for {name} failed to compile:\n"
        f"{result.stderr}\n\n--- generated source ---\n{r.solidity}"
    )
    assert "Binary:" in result.stdout
